[package]
name = "kecleon"
version = "0.1.0"
edition = "2021"
authors = ["Daniel Santana <danielsantanarocha@gmail.com>"]

[lib]
crate-type = [ "staticlib" ]
path = "kernel/main.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
